// From the names Lumo had before to its own, once.
//
// Lumo started as a fork of another app, and up to 0.4.0 kept that app's names
// for everything the user never sees: its folders, the service name of its keys
// in the system keychain, the app identifier (which names the WebView's own
// folder, where the chat history is), the relay's file name, the fields the
// relay adds to an event, and the files and hook groups it writes into other
// agents' configs. Those names live in this file and nowhere else; everything
// else in Lumo uses its own.
//
// At launch, before anything reads a folder or a WebView starts:
//   * the folders move to Lumo's (`folders`), the log is renamed;
//   * the keys move to Lumo's keychain service (`keys`).
// While an agent's config still runs the relay from the old folder (hooks
// installed before, which only the user may rewrite: Settings → Agents →
// Reinstall), the relay is kept there too (`old_relay`); once nothing points
// at it, that folder goes. Events from such a relay, or from an agent that
// tags its own events the old way, are read as Lumo's (`payload`). Settings →
// Agents recognises and replaces the old files and groups (`agent_files`,
// `OLD_GROUP`, `OLD_MARKER`).

use std::path::{Path, PathBuf};

use serde_json::Value;

use crate::{platform, settings};

/// The old name, as folders and files had it.
const OLD: &str = "coucou";
const OLD_TITLE: &str = "Coucou";
/// The app identifier before (the WebView's folder, the keychain service).
const OLD_IDENTIFIER: &str = "fr.louisraille.coucou";

/// The relay's old file name, still in hook commands written before.
pub const OLD_RELAY: &str = "coucou-hook";
/// The hook group Antigravity's hooks.json had for Lumo.
pub const OLD_GROUP: &str = "coucou";
/// What the plugin files Lumo wrote said about themselves.
pub const OLD_MARKER: &str = "generated by Coucou";
/// The autostart entry's old name.
pub const OLD_AUTOSTART: &str = "Coucou";

// ── Folders ───────────────────────────────────────────────────────────────────

/// The old folder beside `new` (same parent), by its old name.
fn beside(new: &Path, name: &str) -> Option<PathBuf> {
    new.parent().map(|p| p.join(name))
}

/// The old data folder name on this OS.
fn old_folder_name() -> &'static str {
    if cfg!(windows) {
        OLD_TITLE
    } else {
        OLD
    }
}

/// The old local data folder (the relay, the inbox, the log, the recap).
fn old_local() -> Option<PathBuf> {
    beside(&settings::local_dir(), old_folder_name())
}

/// The old relay folder: what hooks installed before still run.
fn old_bin() -> Option<PathBuf> {
    old_local().map(|d| d.join("bin"))
}

/// Moves what is in `old` into `new`, entry by entry, without replacing
/// anything already there; `skip` stays where it is. `old` goes once empty.
fn move_into(old: &Path, new: &Path, skip: &[&str]) {
    let Ok(read) = std::fs::read_dir(old) else { return };
    if std::fs::create_dir_all(new).is_err() {
        return;
    }
    for entry in read.flatten() {
        let name = entry.file_name();
        if skip.iter().any(|s| name.to_string_lossy().eq_ignore_ascii_case(s)) {
            continue;
        }
        let to = new.join(&name);
        if !to.exists() {
            let _ = std::fs::rename(entry.path(), &to);
        }
    }
    // Only if nothing is left (`skip`, or what could not move).
    let _ = std::fs::remove_dir(old);
}

/// Moves `old` to `new` whole when `new` isn't there yet, else entry by entry.
fn take_over(old: &Path, new: &Path, skip: &[&str]) {
    if !old.is_dir() {
        return;
    }
    if !new.exists() && skip.is_empty() {
        if let Some(parent) = new.parent() {
            let _ = std::fs::create_dir_all(parent);
        }
        if std::fs::rename(old, new).is_ok() {
            return;
        }
    }
    move_into(old, new, skip);
}

/// The folders, before anything opens them: preferences, the local data
/// (without the relay, see `old_relay`), the WebView's data (the chat
/// history), the log's name, and the folder Claude Code works in.
pub fn folders() {
    let local = settings::local_dir();
    // The WebView's folder first: on Windows it is the local data folder itself.
    if let Some(old) = beside(&local, OLD_IDENTIFIER) {
        let web = local.parent().map(|p| p.join(crate::IDENTIFIER)).unwrap_or_else(|| local.clone());
        take_over(&old, &web, &[]);
    }
    if let Some(old) = beside(&settings::config_dir(), old_folder_name()) {
        take_over(&old, &settings::config_dir(), &[]);
    }
    if let Some(old) = old_local() {
        take_over(&old, &local, &["bin"]);
    }
    let log = local.join(format!("{OLD}.log"));
    if log.exists() {
        let _ = std::fs::rename(&log, local.join("lumo.log"));
    }
    #[cfg(target_os = "linux")]
    if let Some(cache) = std::env::var_os("XDG_CACHE_HOME").map(PathBuf::from).or_else(|| Some(platform::home_dir().join(".cache"))) {
        let _ = std::fs::remove_dir_all(cache.join(OLD));
    }
    let work = crate::claude_code::work_dir();
    take_over(&platform::home_dir().join(OLD_TITLE), &work, &[]);
}

// ── Keys ──────────────────────────────────────────────────────────────────────

/// Each key in the keychain moves to Lumo's service, unless Lumo already has one.
pub fn keys() {
    for key in crate::secrets::KNOWN_KEYS {
        let Ok(old) = keyring::Entry::new(OLD_IDENTIFIER, key) else { continue };
        let Ok(value) = old.get_password() else { continue };
        if !crate::secrets::present(key) && !value.is_empty() && crate::secrets::set(key, &value).is_err() {
            continue; // kept where it was: nothing is lost
        }
        let _ = old.delete_credential();
    }
}

// ── The relay hooks installed before still run ────────────────────────────────

/// Some config still runs the relay from the old folder, or by its old name.
pub fn mentions_old_relay(text: &str) -> bool {
    let text = text.to_lowercase().replace('\\', "/");
    if text.contains(OLD_RELAY) {
        return true;
    }
    old_bin().is_some_and(|bin| text.contains(&bin.to_string_lossy().to_lowercase().replace('\\', "/")))
}

/// Keeps the relay in the old folder, under both its names, while a config in
/// `configs` still runs it from there (`install` copies it); once none does,
/// the old folder goes.
pub fn old_relay(src: &Path, configs: &[PathBuf], install: fn(&Path, &Path)) {
    let Some(bin) = old_bin() else { return };
    if !bin.is_dir() {
        return;
    }
    let used = configs.iter().any(|p| std::fs::read_to_string(p).is_ok_and(|t| mentions_old_relay(&t)));
    if used {
        install(src, &bin.join(platform::HOOK_EXE));
        let old_name = format!("{OLD_RELAY}{}", if cfg!(windows) { ".exe" } else { "" });
        install(src, &bin.join(old_name));
        return;
    }
    let _ = std::fs::remove_dir_all(&bin);
    if let Some(old) = old_local() {
        let _ = std::fs::remove_dir(old);
    }
}

// ── Events ────────────────────────────────────────────────────────────────────

/// An event as Lumo reads it: the old field names (`coucou_agent`…) become
/// Lumo's (`lumo_agent`…), unless the event has both.
pub fn payload(payload: &mut Value) {
    let Some(map) = payload.as_object_mut() else { return };
    let old: Vec<String> = map.keys().filter(|k| k.starts_with(&format!("{OLD}_"))).cloned().collect();
    for key in old {
        let Some(value) = map.remove(&key) else { continue };
        let new = format!("lumo_{}", &key[OLD.len() + 1..]);
        map.entry(new).or_insert(value);
    }
}

// ── Other agents' files ───────────────────────────────────────────────────────

/// The files Lumo wrote for an agent under the old name, which Settings →
/// Agents removes when it installs (or uninstalls) Lumo's own.
pub fn agent_files(agent: &str, home: &Path) -> Vec<PathBuf> {
    match agent {
        "copilot" => vec![home.join(".copilot").join("hooks").join(format!("{OLD}.json"))],
        "opencode" => vec![home.join(".config").join("opencode").join("plugins").join(format!("{OLD}.js"))],
        "amp" => vec![home.join(".config").join("amp").join("plugins").join(format!("{OLD}.ts"))],
        "hermes" => {
            let dir = home.join(".hermes").join("plugins").join(OLD);
            vec![dir.join("__init__.py"), dir.join("plugin.yaml")]
        }
        _ => Vec::new(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn old_field_names_become_lumo_s_and_never_win() {
        let mut v = json!({ "coucou_agent": "codex", "coucou_island": true, "cwd": "/x" });
        payload(&mut v);
        assert_eq!(v, json!({ "lumo_agent": "codex", "lumo_island": true, "cwd": "/x" }));
        let mut both = json!({ "coucou_agent": "old", "lumo_agent": "new" });
        payload(&mut both);
        assert_eq!(both, json!({ "lumo_agent": "new" }));
    }

    #[test]
    fn a_config_that_still_runs_the_old_relay_is_seen() {
        assert!(mentions_old_relay(r#""C:/Users/me/AppData/Local/X/bin/coucou-hook.exe" Stop"#));
        let bin = old_bin().unwrap().join("lumo-hook").to_string_lossy().to_string();
        assert!(mentions_old_relay(&format!("'{bin}' --agent codex")));
        assert!(!mentions_old_relay(&format!("'{}' Stop", settings::hook_exe_path().display())));
    }

    #[test]
    fn moving_keeps_what_is_there_and_what_is_skipped() {
        let base = std::env::temp_dir().join(format!("lumo-migrate-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&base);
        let (old, new) = (base.join("old"), base.join("new"));
        std::fs::create_dir_all(old.join("bin")).unwrap();
        std::fs::create_dir_all(old.join("inbox")).unwrap();
        std::fs::create_dir_all(&new).unwrap();
        std::fs::write(old.join("recap.json"), "old").unwrap();
        std::fs::write(old.join("settings.json"), "old").unwrap();
        std::fs::write(new.join("settings.json"), "new").unwrap();
        take_over(&old, &new, &["bin"]);
        assert_eq!(std::fs::read_to_string(new.join("recap.json")).unwrap(), "old");
        assert_eq!(std::fs::read_to_string(new.join("settings.json")).unwrap(), "new", "never replaced");
        assert!(new.join("inbox").is_dir() && !new.join("bin").exists());
        assert!(old.join("bin").is_dir(), "the relay stays for the hooks written before");

        // A folder Lumo doesn't have yet moves whole.
        let (a, b) = (base.join("a"), base.join("deep").join("b"));
        std::fs::create_dir_all(a.join("EBWebView")).unwrap();
        take_over(&a, &b, &[]);
        assert!(b.join("EBWebView").is_dir() && !a.exists());
        let _ = std::fs::remove_dir_all(&base);
    }

    #[test]
    fn the_old_plugin_files_are_known_for_every_plugin_agent() {
        let home = Path::new("/home/me");
        assert!(agent_files("copilot", home)[0].ends_with(".copilot/hooks/coucou.json"));
        assert_eq!(agent_files("hermes", home).len(), 2);
        assert!(agent_files("codex", home).is_empty());
    }
}
